apiVersion: v1
kind: Pod
metadata:
  name: k6-load-test
  labels:
    app: k6-load-test
spec:
  containers:
  - name: k6
    image: grafana/k6:0.49.0
    command: [ "sh", "-c" ]
    args:
      - |
        k6 run /scripts/test.js && \
        echo "Test completed. The HTML report is saved in /resultados."
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
      - name: test-scripts
        mountPath: /scripts
      - name: resultados-volume
        mountPath: /resultados
    workingDir: /scripts
  volumes:
    - name: test-scripts
      hostPath:
        path: /Users/erik/workspace/k8s-k6-dashboard
        type: Directory
    - name: resultados-volume
      hostPath:
        path: /Users/erik/workspace/k8s-k6-dashboard/resultados
        type: Directory
